import Head from 'next/head'
import React from 'react'
import Carddetail from '../components/cardDetail'
import NavbarSearch from '../components/navbarSearch'

const about = () => {
  return (
    <div>
      <Head>
        <title>Coursurf - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <link rel="apple-touch-icon" href="image2.png"></link>
      </Head>
      <NavbarSearch />
      <Carddetail />
    </div>

  )
}

export default about