import Head from 'next/head';
import Card from '../components/cardMain';
import Navbar from '../components/navbar';
import Search from '../components/search';
import { CardSkeleton } from '../components/skeleton';
import Titles from '../components/titles';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coursurf</title>
        <meta charSet='UTF-8' />
        <meta name='description' content="Coursurf is the ultimate online platform for finding and comparing courses from top providers. With Coursurf, you can easily search and compare courses based on your interests, budget, and learning goals. Whether you're looking to upskill in a new subject, enhance your career prospects, or simply follow a personal passion, Coursurf provides you with all the information you need to make informed decisions about your education. Our website aggregates courses from leading providers, so you can compare options and find the perfect course for you. Get started today and take the first step towards reaching your educational goals." />
        <meta name='keywords' content='coursurf, next, course provider, free courses' />
        <meta name='author' content='Adithya SK, Sarang Kumar, Sakthe Balan' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/images/icons/apple-touch-icon.png" />
        <meta name="theme-color" content="#FD8A45"/>

        <link rel='manifest' href='/manifest.json'/>
      </Head>
      <Navbar />

      <section id='hero-section'>
        <div className="content">
          <h1>Let&apos;s get you a new course</h1>
          <Search />
        </div>
      </section>
      <section id="trending-courses">
        <Titles certificate="Master's and Bachelor's Degrees" heading="Find a top degree that fits your life" desc="Breakthrough pricing on 100% online degrees from top universities." />
        <div className="card-container">
          <CardSkeleton />
          <CardSkeleton />
          <CardSkeleton />
          <Card />
          <Card />
          <Card />
        </div>
      </section>

      <section id='institutions'>
        <Titles certificate="Courses and Specializations"
          heading="Advance your career with new skills"
          desc="Choose from over 4,000 courses in topics like business analytics, graphic design, Python, and more." />
        <div className="card-container">
          <CardSkeleton />
          <Card />
          <CardSkeleton />
          <CardSkeleton />
          <CardSkeleton />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>

      </section>

    </div>
  );
}
